sudo: false
language: ruby
cache: bundler
rvm:
- 2.2.2
- 2.3.1

gemfile:
  - Gemfile

env: DATABASE_URL=postgres://postgres@localhost/torque_postgresql_test

before_script:
- psql -c 'create database torque_postgresql_test;' -U postgres -h localhost

# notifications:
#   email:
#   - git@danmcclain.net
addons:
  postgresql: '9.3'
