sudo: false
language: ruby
cache: bundler
rvm:
- 2.0.0
- 2.1.2
- 2.2.0
- 2.3.1

gemfile:
  - Gemfile

env: DATABASE_URL=postgres://postgres@localhost/torque_postgresql_test

before_script:
- psql -c 'create database torque_postgresql_test;' -U postgres -h localhost
- bundle exec rake db:migrate

# notifications:
#   email:
#   - git@danmcclain.net
addons:
  postgresql: '9.3'
